name: dry-run
'on':
  push:
  pull_request:
    branches:
      - master
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout-repo
        uses: actions/checkout@master

      - name: Set environment
        id: set-environment
        run: |
          echo "GIT_BRANCH=${GITHUB_REF##*/}"  >> $GITHUB_OUTPUT

  sre-portal-infra-dryru:
    name: sre-portal-infra dryrun
    runs-on: ubuntu-latest
    env:
      environment: '${{ steps.set-environment.outputs.GIT_BRANCH }}'
    steps:
      - name: Checkout Repository
        id: checkout-repo
        uses: actions/checkout@master

      - name: Get AWS Role
        id: get-role
        run: |
          if [ "${environment}" == "master" ]; then
              echo "logging to prod...."
              export role_to_assume="${{ secrets.SRE_PORTAL_DEPLOYMENT_ROLE_PROD }}"
          elif [ "${environment}" == "dev" ]; then
              echo "logging to dev...."
              export role_to_assume="${{ secrets.SRE_PORTAL_DEPLOYMENT_ROLE_DEV }}"
          else
              echo "logging to dev.."
              export role_to_assume="${{ secrets.SRE_PORTAL_DEPLOYMENT_ROLE_DEV }}"
          fi
        continue-on-error: false

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ steps.get-role.outputs.role_to_assume }}

      - name: Get text file from S3
        id: get-version
        run: |
          if [ "${environment}" == "master" ]; then
              aws s3 cp s3://sre-sreportal-backend-prod/version.txt version.txt
          elif [ "${environment}" == "dev" ]; then
              aws s3 cp s3://sre-sreportal-backend-dev/version.txt version.txt
          else
              aws s3 cp s3://sre-sreportal-backend-dev/version.txt version.txt
          fi
        continue-on-error: false

      - name: Setpup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.3

      - name: Terraform Init
        id: initialise-terraform
        run: terraform init -backend-config="backends/$environment.s3.tfbackend"
        continue-on-error: false

      - name: Terraform Format
        id: indenting-terraform
        run: terraform fmt
        continue-on-error: false

      - name: Terraform Validate
        id: syntax-check
        run: terraform validate
        continue-on-error: false

      - name: Terraform List
        id: resource-list
        run: terraform state list
        continue-on-error: false

      - name: Terraform Plan
        id: terraform-plan
        run: |
          terraform plan -var-file=variables/variable-$environment.tfvars -no-color
        continue-on-error: false
